### ISSUE TITLE
Where does the server handles the ack returned by the client?

### ISSUE THREAD

**Issue by tyh-sugar** [Schastlivcev/JavaLab#1]
I am using java language,
I see the ru.kpfu.itis.rodsher.jlmq.Consumer#receive, and there is a call to acknowledge() in it,
may I ask where the server side handles this ack?
Thank you~

**Comment by Schastlivcev** [comment]
See ru.kpfu.itis.rodsher.jlmq.websocket.handlers.InboundStompChannelInterceptor#preSend. The problem is that SimpleMessageBroker can't handle Acknowledge messages, they're just not supported. You should use more powerful solutions like RabbitMQ, where you won't need to write such things
